apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "smtp-aws-ses.fullname" . }}-config
data:
  RELAY_HOST: "email-smtp.{{ .Values.aws.region }}.amazonaws.com"
  RELAY_PORT: "{{ .Values.aws.ses.port }}"
  FROM_EMAIL: "{{ .Values.aws.ses.fromEmail }}"
  TO_EMAIL: "{{ .Values.aws.ses.toEmail }}"
  RECIPIENT_RESTRICTIONS: {{ .Values.recipientRestrictions | default "permit_mynetworks, permit_sasl_authenticated, reject_unauth_destination" }}
  USE_TLS: {{ .Values.aws.ses.useTls | default "yes" }}
  TLS_VERIFY: {{ .Values.aws.ses.tlsVerify | default "yes" }}