apiVersion: v1
kind: Secret
metadata:
  name: {{ include "smtp-aws-ses.fullname" . }}-secrets
type: Opaque
data:
  RELAY_LOGIN: {{ .Values.aws.accessKeyId | b64enc }}
  RELAY_PASSWORD: {{ .Values.aws.secretAccessKey | b64enc }}